# Generated by Django 5.2.14 on 2026-05-26 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transcriptchunk',
            new_name='videos_tran_video_i_7b5e62_idx',
            old_name='videos_tran_video_i_d293a1_idx',
        ),
        migrations.RenameIndex(
            model_name='transcriptsegment',
            new_name='videos_tran_video_i_4709ee_idx',
            old_name='videos_tran_video_i_8703a4_idx',
        ),
        migrations.RenameIndex(
            model_name='viralmomentcandidate',
            new_name='videos_vira_video_i_fc2d7f_idx',
            old_name='videos_vira_video_i_475a8c_idx',
        ),
    ]
